/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatserver;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @version 0.0.1
 * @author Rocchi Francesco
 */
public class GUI extends javax.swing.JFrame {
	ChatServer chat;

	/**
	 * Creates new form GUI
	 *
	 * @param chat
	 */
	public GUI(ChatServer chat) {
		this.chat = chat;
		initComponents();
		this.setVisible(true);
	}

	public void updateUsersTable() {
		usersTable.setModel(new DefaultTableModel(chat.getTable(), chat.getColumnTitle()));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        addUserButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        retypePasswordTextField = new javax.swing.JPasswordField();
        usersManagement = new javax.swing.JFrame();
        addMultipleUsersButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        openUsersManagement = new javax.swing.JButton();

        addUserFrame.setTitle("Aggiungi utente");
        addUserFrame.setMinimumSize(new java.awt.Dimension(380, 258));

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        addUserButton.setText("Aggiungi utente");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Ripeti password:");

        javax.swing.GroupLayout addUserFrameLayout = new javax.swing.GroupLayout(addUserFrame.getContentPane());
        addUserFrame.getContentPane().setLayout(addUserFrameLayout);
        addUserFrameLayout.setHorizontalGroup(
            addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTextField)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addUserFrameLayout.createSequentialGroup()
                        .addGroup(addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(retypePasswordTextField))
                .addContainerGap())
            .addGroup(addUserFrameLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        addUserFrameLayout.setVerticalGroup(
            addUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retypePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        usersManagement.setTitle("Utenti");
        usersManagement.setMinimumSize(new java.awt.Dimension(400, 260));

        addMultipleUsersButton.setText("Aggiungi utente");
        addMultipleUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMultipleUsersButtonActionPerformed(evt);
            }
        });

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(usersTable);

        jButton1.setText("Rimuovi utente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersManagementLayout = new javax.swing.GroupLayout(usersManagement.getContentPane());
        usersManagement.getContentPane().setLayout(usersManagementLayout);
        usersManagementLayout.setHorizontalGroup(
            usersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersManagementLayout.createSequentialGroup()
                        .addComponent(addMultipleUsersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        usersManagementLayout.setVerticalGroup(
            usersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersManagementLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(usersManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMultipleUsersButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        startButton.setText("Avvia server");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusLabel.setText("•");

        ipField.setText("192.168.1.24");

        portField.setText("3306");

        jLabel3.setText("IP:");

        jLabel4.setText("Port:");

        openUsersManagement.setText("Gestisci Utenti");
        openUsersManagement.setEnabled(false);
        openUsersManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openUsersManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel)
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openUsersManagement)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel4)))
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openUsersManagement)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
	if (startButton.getText().equals("Avvia server") || startButton.getText().equals("Riavvia server")) {
		switch (chat.createDBConnection(ipField.getText(), portField.getText())) {
			case -2:
				JOptionPane.showMessageDialog(this, "Driver JDBC non trovato!", "Errore!", JOptionPane.ERROR_MESSAGE);
				break;
			case 0:				 //host and port errors
				JOptionPane.showMessageDialog(this, "Attenzione!\nIndirizzo Host o porta sbagliata (o non raggiungibile)!", "ERRORE!", JOptionPane.ERROR_MESSAGE, null);
				break;
			case 1045:				//username and password errrors
				JOptionPane.showMessageDialog(this, "Attenzione!\nNome utente o password sbagliata!", "ERRORE!", JOptionPane.ERROR_MESSAGE, null);
				break;
			case 1049:				//database not found errors
				JOptionPane.showMessageDialog(this, "Attenzione!\nNome database errato!", "ERRORE!", JOptionPane.ERROR_MESSAGE, null);
				break;
			default:				//no errors found
				startButton.setText("Termina server");
				statusLabel.setForeground(Color.green);
				openUsersManagement.setEnabled(true);
				this.updateUsersTable();
		}
	} else {
		startButton.setText("Riavvia server");
		statusLabel.setForeground(Color.red);
		openUsersManagement.setEnabled(false);
		chat.disconnectFromDB();
	}
	}//GEN-LAST:event_startButtonActionPerformed

	private void addMultipleUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMultipleUsersButtonActionPerformed
		addUserFrame.setVisible(true);
	}//GEN-LAST:event_addMultipleUsersButtonActionPerformed

	private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
	if (!usernameTextField.getText().isEmpty() || !passwordTextField.getText().isEmpty()) {
		if(passwordTextField.getText().equals(retypePasswordTextField.getText())) {
			chat.insertUser(usernameTextField.getText(), passwordTextField.getText().toString());
			updateUsersTable();
			usernameTextField.setText("");
			passwordTextField.setText("");
			retypePasswordTextField.setText("");
		} else
			JOptionPane.showMessageDialog(this, "Attenzione!\nLe password non corrispondono!", "ERRORE!", JOptionPane.ERROR_MESSAGE, null);
	}
	else
		JOptionPane.showMessageDialog(this, "Attenzione!\nCampi username e/o password non compilati!", "ERRORE!", JOptionPane.ERROR_MESSAGE, null);
	}//GEN-LAST:event_addUserButtonActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		chat.deleteUser(usersTable.getSelectedRow());
		updateUsersTable();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void openUsersManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openUsersManagementActionPerformed
		usersManagement.setVisible(true);
	}//GEN-LAST:event_openUsersManagementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMultipleUsersButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JFrame addUserFrame;
    private javax.swing.JTextField ipField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openUsersManagement;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField portField;
    private javax.swing.JPasswordField retypePasswordTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JFrame usersManagement;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
